/* A progress diagram, not a biological reconstruction. Uses existing saved quiz results. */
(function(root){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#27817c','#466fb5','#9565ad','#b66e29','#be5268'];
function model(C,E,state){return C.blocks.map(b=>{const lessons=C.lessons.filter(l=>l.block===b.id),groups=[...lessons.flatMap(l=>l.steps),C.cases.find(g=>g.block===b.id)],total=groups.reduce((n,g)=>n+g.questions.length,0),solved=groups.reduce((n,g)=>n+g.questions.filter((_,i)=>E.resolved(state,`${g.id}:${i}`)).length,0);return {id:b.id,title:b.title,solved,total,ratio:solved/total,done:E.blockDone(state,b),href:'#lesson/'+(lessons.flatMap(l=>l.steps).find(s=>!E.complete(state,s))?.id||lessons[0].steps[0].id),caseHref:'#case/'+b.id};});}
function sector(start,end){const point=a=>[150+110*Math.cos(a),145+110*Math.sin(a)],a=point(start),b=point(end);return `M150 145 L${a.join(' ')} A110 110 0 ${end-start>Math.PI?1:0} 1 ${b.join(' ')} Z`;}
function render(C,E,state){const items=model(C,E,state),spatial=C.id.includes('spatial'),done=E.graduated(state),trophies=E.trophies(state).length;
const shapes=items.map((b,i)=>{let marks='';if(!spatial){const start=-Math.PI/2+i*2*Math.PI/5,end=start+2*Math.PI/5;marks=`<path d="${sector(start,end)}" fill="#e4e9ed" stroke="white" stroke-width="3"/>`+(b.ratio?`<path d="${sector(start,start+(end-start)*b.ratio)}" fill="${colors[i]}" stroke="white" stroke-width="2"/>`:'');const mid=(start+end)/2;marks+=`<text x="${150+88*Math.cos(mid)}" y="${151+88*Math.sin(mid)}" text-anchor="middle" fill="#102738" stroke="white" stroke-width="3" paint-order="stroke" font-size="17" font-weight="700">${b.id}</text>`;}else{const origins=[[45,50],[153,50],[99,120],[45,190],[153,190]],o=origins[i];for(let k=0;k<12;k++){const x=o[0]+(k%4)*24+(Math.floor(k/4)%2)*5,y=o[1]+Math.floor(k/4)*20;marks+=`<circle cx="${x}" cy="${y}" r="9" fill="${k/12<b.ratio?colors[i]:'#e4e9ed'}" stroke="white" stroke-width="1"/>`;}marks+=`<text x="${o[0]+38}" y="${o[1]-16}" text-anchor="middle" fill="#102738" font-size="17" font-weight="700">${b.id}</text>`;}return `<a href="${b.href}" aria-label="${esc(b.title)}: ${b.solved} of ${b.total} decisions explored"><title>${esc(b.title)}: ${b.solved}/${b.total}</title>${marks}</a>`;}).join('');
const center=spatial?'':`<circle cx="150" cy="145" r="48" fill="${done?'#f0ca6d':'#142b45'}" stroke="white" stroke-width="4"/><text x="150" y="141" text-anchor="middle" fill="${done?'#142b45':'white'}" font-size="15" font-weight="700">${done?'COMPLETE':'FINAL'}</text><text x="150" y="162" text-anchor="middle" fill="${done?'#142b45':'white'}" font-size="12">${done?'Well done!':'4/5 to pass'}</text>`;
return `<div class="knowledge-journey"><div class="journey-picture"><svg viewBox="0 0 300 290" role="img" aria-label="${spatial?'Tissue-map':'Single-cell'} learning progress: ${trophies} of 5 blocks complete${done?', final challenge passed':''}">${shapes}<a href="#final" aria-label="Final investigation">${center}</a></svg><p>Learning diagram - ${spatial?'regions':'sectors'} represent course blocks.</p></div><div class="journey-content"><p class="eyebrow">Your learning takes shape</p><h2>${spatial?'Build your spatial atlas':'Build your single-cell understanding'}</h2><p>Explore the questions and review feedback to fill each ${spatial?'tissue region':'cell sector'}. Review the lessons and case to earn its exploration trophy. XP and assessment scores track correct answers. Explore in any order.</p><ol class="journey-blocks">${items.map((b,i)=>`<li><a href="${b.href}"><span class="journey-dot" style="background:${colors[i]}">${b.id}</span><span>${esc(b.title)}<small>${b.solved}/${b.total} decisions${b.done?' - Trophy earned':''}</small></span></a><a class="journey-case" href="${b.caseHref}">Case →</a><progress value="${b.solved}" max="${b.total}" aria-label="${esc(b.title)} progress"></progress></li>`).join('')}</ol><div class="journey-finish"><strong>${done?'Finish line reached!':'Your finish line'}</strong><p>${done?'You connected the five blocks and passed the final investigation. Share what you learned.':`Earn all five block trophies (${trophies}/5), then score at least 4/5 in the final investigation. Optional mastery challenges deepen your learning.`}</p><a class="btn secondary small" href="${done?'#achievements':'#final'}">${done?'Share your achievement':trophies===5?'Start the final investigation':'Preview the final investigation'} →</a></div></div></div>`;
}
root.LearningJourney={render,model};
})(window);
