(function(root){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qcRows=[['Small lymphocyte',350,700,4,'Low-RNA but plausible singlet'],['T cell',1100,2400,5,'Coherent lineage markers'],['B cell',1400,3200,6,'Coherent lineage markers'],['Large activated cell',2900,11500,8,'High-count singlet is plausible'],['Damaged candidate',280,800,35,'High mitochondrial fraction'],['Mixed-marker candidate',3600,16000,7,'Doublet review needed'],['Low-complexity candidate',120,300,18,'Limited expression support'],['Metabolically active cell',1800,4800,22,'Biological context required']];
const matrix=[[0,3,0,0,1,0],[2,0,0,0,0,0],[0,0,7,0,0,0],[0,1,0,4,0,0],[0,0,0,0,0,2]];
const pbRows=[];for(let d=1;d<=2;d++)for(const c of ['Control','Stimulated'])for(const t of ['T cell','B cell'])for(let i=1;i<=2;i++)pbRows.push({donor:'D'+d,condition:c,type:t,count:(t==='T cell'?5:2)+(c==='Stimulated'?3:0)+d+i});
const M={
 qc:(genes,mt,counts)=>qcRows.map(r=>({...{name:r[0],genes:r[1],counts:r[2],mito:r[3],note:r[4]},keep:r[1]>=genes&&r[3]<=mt&&r[2]<=counts})),
 composition:a=>({a,b:20,total:a+20,bPercent:100*20/(a+20)}),
 normalize:(gene,total)=>Math.log1p(gene/total*10000),
 sparse:()=>matrix.flatMap((row,i)=>row.flatMap((v,j)=>v?[[i+1,j+1,v]]:[])),
 aggregate:level=>{const groups={};for(const r of pbRows){const key=level==='condition'?r.condition:level==='donor'?[r.donor,r.condition].join(' / '):[r.donor,r.condition,r.type].join(' / ');if(!groups[key])groups[key]={count:0,cells:0};groups[key].count+=r.count;groups[key].cells++;}return groups;},
 trajectory:root=>{const edges=[[0,1],[1,2],[2,3],[2,4]],dist=Array(5).fill(Infinity);dist[root]=0;const queue=[root];while(queue.length){const n=queue.shift();for(const[a,b]of edges){const next=a===n?b:b===n?a:-1;if(next>=0&&dist[next]===Infinity){dist[next]=dist[n]+1;queue.push(next);}}}return dist;}
};root.LabModels=M;
const wrap=(label,title,text,content)=>`<section class="interactive"><p class="eyebrow">${label}</p><h3>${title}</h3><p>${text}</p>${content}</section>`;
const button=(id,text,active=false)=>`<button class="btn secondary small" id="${id}" aria-pressed="${active}">${text}</button>`;
function render(type){switch(type){
case'files':return wrap('Explore the output','Which file would you open?','Select a file to see what it contains and where it belongs in the workflow.',`<div class="control-row" id="file-choices">${['FASTQ','BAM','matrix.mtx.gz','features.tsv.gz','barcodes.tsv.gz','filtered_feature_bc_matrix.h5','web_summary.html','analysis.rds'].map((f,i)=>`<button class="btn secondary small file-choice" data-file="${i}" aria-pressed="${i===0}">${f}</button>`).join('')}</div><div id="file-output" class="lab-output" aria-live="polite"></div>`);
case'sparse':return wrap('Synthetic matrix','Same values, different storage','Switch representations. Nothing about the measured expression changes.',`<div class="control-row">${button('dense-view','Dense view',true)}${button('sparse-view','Sparse entries')}</div><div class="table-scroll" id="matrix-output"></div><label for="memory-cells">Cells in a larger example: <strong id="memory-value">100,000</strong></label><input id="memory-cells" type="range" min="1000" max="100000" step="1000" value="100000"><p id="memory-output" class="lab-output" aria-live="polite"></p><p class="help">Memory illustration: 20,000 genes, 64-bit values and 5% nonzero entries. Sparse estimate uses 32-bit row indices and column pointers; actual objects add overhead.</p>`);
case'qc':return wrap('Synthetic cells · thresholds are examples','What does your filter remove?','Adjust three common metrics. A retained row is not a validated cell, and a removed row is not automatically an artifact.',`<div class="slider-pair"><div><label for="min-genes">Minimum genes: <strong id="genes-value">200</strong></label><input type="range" id="min-genes" min="0" max="2000" step="50" value="200"></div><div><label for="max-mito">Maximum mitochondrial percentage: <strong id="mito-value">20%</strong></label><input type="range" id="max-mito" min="5" max="40" step="1" value="20"></div></div><label for="max-counts">Maximum UMIs: <strong id="counts-value">20,000</strong></label><input type="range" id="max-counts" min="2000" max="20000" step="1000" value="20000"><div class="table-scroll"><table class="mini-table"><thead><tr><th>Candidate</th><th>Genes</th><th>UMIs</th><th>MT%</th><th>Result</th></tr></thead><tbody id="qc-body"></tbody></table></div><p id="qc-result" class="lab-output" aria-live="polite"></p><details class="more"><summary>Reveal biological context</summary>${qcRows.map(r=>`<p><strong>${r[0]}:</strong> ${r[4]}.</p>`).join('')}</details>`);
case'normalize':return wrap('Synthetic counts','A relative scale changes the comparison','Gene G has 100 counts in cell A (total 1,000) and 200 counts in cell B. Change cell B’s total while keeping its gene G count fixed.',`<label for="norm-total">Cell B total counts: <strong id="norm-total-value">2,000</strong></label><input id="norm-total" type="range" min="1000" max="8000" step="100" value="2000"><div class="table-scroll"><table class="mini-table"><thead><tr><th>Cell</th><th>Gene G counts</th><th>Total</th><th>log(1 + counts / total × 10,000)</th></tr></thead><tbody id="norm-output"></tbody></table></div><p class="lab-output">The observed count and normalized value answer different questions. This arithmetic does not establish absolute RNA content or transcription rate.</p>`);
case'umap':return wrap('Real 10x PBMC3k data','Same cells, two UMAP settings','Both layouts were computed from the same 20 supplied PCs. Reference labels are fixed. Switching layouts does not rerun clustering or alter the expression measurements.',`<div class="control-row">${button('umap-a','10 neighbors · min_dist 0.1',true)}${button('umap-b','40 neighbors · min_dist 0.6')}</div><label for="umap-color">Color by</label><select id="umap-color"><option value="type">Supplied cell-type labels</option><option value="counts">Total counts (log color scale)</option></select><canvas id="umap-canvas" class="plot" width="850" height="520" role="img" aria-label="Interactive real PBMC UMAP"></canvas><div id="umap-legend" class="legend"></div><p id="umap-summary" class="data-caption" aria-live="polite"></p><details class="more"><summary>View cell counts as a table</summary><div id="umap-table" class="table-scroll"></div></details>`);
case'composition':return wrap('Synthetic arithmetic · not tissue counts','A stable population can lose percentage','Start with 80 T cells and 20 B cells. Increase only T cells. B-cell counts stay fixed.',`<label for="composition-range">T-cell count: <strong id="composition-value">80</strong></label><input id="composition-range" type="range" min="80" max="400" step="10" value="80"><div class="stackbar" id="composition-bar"></div><div class="metric-grid"><div class="metric"><strong id="b-count">20</strong><span>B-cell count</span></div><div class="metric"><strong id="b-fraction">20%</strong><span>B-cell fraction</span></div><div class="metric"><strong id="all-count">100</strong><span>Total cells</span></div></div><p class="lab-output" id="composition-note" aria-live="polite"></p>`);
case'pseudobulk':return wrap('Synthetic count aggregation','Keep the donor and cell type','The input contains 16 cells: two donors, two conditions, two cell types and two cells in each combination. The displayed value is the count of one illustrative gene.',`<label for="pb-group">Aggregate by</label><select id="pb-group"><option value="condition">Condition only</option><option value="donor">Donor + condition</option><option value="type">Donor + condition + cell type</option></select><div class="table-scroll"><table class="mini-table"><thead><tr><th>Group</th><th>Cells</th><th>Summed counts</th></tr></thead><tbody id="pb-body"></tbody></table></div><p class="lab-output" id="pb-note" aria-live="polite"></p><details class="more"><summary>Inspect the input cells</summary><div class="table-scroll"><table class="mini-table"><thead><tr><th>Donor</th><th>Condition</th><th>Type</th><th>Count</th></tr></thead><tbody>${pbRows.map(r=>`<tr><td>${r.donor}</td><td>${r.condition}</td><td>${r.type}</td><td>${r.count}</td></tr>`).join('')}</tbody></table></div></details>`);
case'de':return wrap('Synthetic outputs · not fitted tests','Choose a defensible gene interpretation','Three hypothetical genes illustrate different evidence. These values were invented for teaching, not computed from PBMC data.',`<div class="table-scroll"><table class="mini-table"><thead><tr><th>Gene</th><th>log2 fold change</th><th>FDR</th><th>Donor pattern</th></tr></thead><tbody><tr><td>Gene A</td><td>0.03</td><td>0.00001</td><td>Consistent but very small</td></tr><tr><td>Gene B</td><td>1.2</td><td>0.01</td><td>Consistent across donors</td></tr><tr><td>Gene C</td><td>2.5</td><td>0.08</td><td>Driven by one donor</td></tr></tbody></table></div><div class="control-row">${button('deg-a','Interpret Gene A')}${button('deg-b','Interpret Gene B')}${button('deg-c','Interpret Gene C')}</div><p class="lab-output" id="de-output" aria-live="polite">Select a gene to inspect the evidence.</p>`);
case'signaling':return wrap('Synthetic evidence ladder','How strong is the signaling claim?','Select the evidence actually available. Each addition changes what can reasonably be argued.',`<label for="signal-level">Available evidence</label><select id="signal-level"><option value="0">Ligand and receptor RNA in dissociated cell types</option><option value="1">RNA plus independent spatial/protein support</option><option value="2">Additional targeted perturbation and response</option></select><p id="signal-output" class="lab-output" aria-live="polite"></p>`);
case'trajectory':return wrap('Synthetic fixed graph · not Slingshot output','Where does your progression begin?','Change the root on the same graph. Colors show relative graph distance from that root, not fitted Slingshot pseudotime or elapsed time.',`<label for="trajectory-root">Assumed root</label><select id="trajectory-root"><option value="0">State A: candidate starting state</option><option value="3">State D: one terminal candidate</option></select><svg id="trajectory-svg" class="plot" viewBox="0 0 720 260" role="img" aria-label="Synthetic branching graph with root-dependent ordering"></svg><p id="trajectory-output" class="lab-output" aria-live="polite"></p><p class="help">A real root needs supporting biology. Changing a selector does not establish a lineage.</p>`);
default:return'';}}
function bind(){
if($('#file-choices')){const info=[['Sequencing reads','FASTQ stores read sequences and quality scores. It is input to primary processing, not the normal entry to the Seurat exploration here.'],['Aligned reads','BAM stores alignments. Preserve it when useful, but you normally start the basic Seurat workflow from the count matrix.'],['Sparse matrix values','The MTX file needs the feature and barcode files to identify its rows and columns.'],['Feature identities','This TSV links matrix rows to feature identifiers and names. It may distinguish RNA and other modalities.'],['Barcode identities','This TSV identifies matrix columns. Retain sample identity because barcodes can recur across libraries.'],['A filtered count matrix','The H5 container includes cell-associated barcodes and counts. Filtered does not mean normalized or fully QC-reviewed.'],['Processing summary','Review Cell Ranger processing metrics, reference and run context before downstream analysis.'],['Saved R analysis object','An RDS file can preserve a Seurat object, including counts, transformations, metadata and results that were stored.']];const show=i=>{$('#file-output').innerHTML=`<strong>${info[i][0]}</strong><p>${info[i][1]}</p>`;$$('[data-file]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.file)===i)));};$$('[data-file]').forEach(b=>b.onclick=()=>show(Number(b.dataset.file)));show(0);}
if($('#matrix-output')){const draw=sparse=>{$('#dense-view').setAttribute('aria-pressed',String(!sparse));$('#sparse-view').setAttribute('aria-pressed',String(sparse));$('#matrix-output').innerHTML=sparse?`<table class="mini-table matrix"><thead><tr><th>Gene row</th><th>Cell column</th><th>Value</th></tr></thead><tbody>${M.sparse().map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="help">Coordinate-list illustration. Practical sparse formats use compressed indices.</p>`:`<table class="mini-table matrix"><thead><tr><th></th>${[1,2,3,4,5,6].map(n=>`<th>Cell ${n}</th>`).join('')}</tr></thead><tbody>${matrix.map((r,i)=>`<tr><th>Gene ${i+1}</th>${r.map(n=>`<td class="${n===0?'zero':''}">${n}</td>`).join('')}</tr>`).join('')}</tbody></table>`;};$('#dense-view').onclick=()=>draw(false);$('#sparse-view').onclick=()=>draw(true);draw(false);const memory=()=>{const n=Number($('#memory-cells').value);$('#memory-value').textContent=n.toLocaleString('en-US');$('#memory-output').textContent=`Dense values: ${(20000*n*8/1e9).toFixed(2)} GB. Approximate sparse arrays at 5% nonzero: ${(20000*n*.05*12/1e9+(n+1)*4/1e9).toFixed(2)} GB. Same matrix dimensions, different storage.`;};$('#memory-cells').oninput=memory;memory();}
if($('#min-genes')){const draw=()=>{const g=+$('#min-genes').value,m=+$('#max-mito').value,c=+$('#max-counts').value;$('#genes-value').textContent=g;$('#mito-value').textContent=m+'%';$('#counts-value').textContent=c.toLocaleString('en-US');const rows=M.qc(g,m,c);$('#qc-body').innerHTML=rows.map(r=>`<tr class="${r.keep?'':'removed'}"><td>${r.name}</td><td>${r.genes}</td><td>${r.counts}</td><td>${r.mito}</td><td>${r.keep?'Retained':'Removed'}</td></tr>`).join('');$('#qc-result').textContent=`${rows.filter(r=>r.keep).length}/8 candidates retained. ${rows[0].keep?'The low-RNA lymphocyte remains.':'The rule removed the plausible low-RNA lymphocyte.'} ${rows[5].keep?'The mixed-marker candidate still needs doublet review.':'The high-count rule removes the mixed-marker candidate, but counts alone do not establish a doublet.'}`;};['#min-genes','#max-mito','#max-counts'].forEach(id=>$(id).oninput=draw);draw();}
if($('#norm-total')){const draw=()=>{const n=+$('#norm-total').value;$('#norm-total-value').textContent=n.toLocaleString('en-US');$('#norm-output').innerHTML=`<tr><td>A</td><td>100</td><td>1,000</td><td>${M.normalize(100,1000).toFixed(3)}</td></tr><tr><td>B</td><td>200</td><td>${n.toLocaleString('en-US')}</td><td>${M.normalize(200,n).toFixed(3)}</td></tr>`;};$('#norm-total').oninput=draw;draw();}
if($('#umap-canvas')){let current=0;const draw=()=>{const d=root.PBMC,canvas=$('#umap-canvas'),ctx=canvas.getContext('2d'),xy=d.embeddings[current],byCount=$('#umap-color').value==='counts';ctx.fillStyle='white';ctx.fillRect(0,0,850,520);const xs=xy.map(p=>p[0]),ys=xy.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);ctx.strokeStyle='#a8b6c7';ctx.beginPath();ctx.moveTo(45,30);ctx.lineTo(45,475);ctx.lineTo(825,475);ctx.stroke();for(let i=0;i<xy.length;i++){const x=65+(xy[i][0]-minX)/(maxX-minX)*735,y=450-(xy[i][1]-minY)/(maxY-minY)*405;ctx.fillStyle=byCount?`hsl(175,55%,${85-Math.min(1,Math.max(0,(Math.log1p(d.counts[i])-6)/3))*62}%)`:d.colors[d.groups[i]];ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(x,y,2.2,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.fillStyle='#526277';ctx.font='14px Arial';ctx.fillText('UMAP 1',735,505);ctx.fillText('UMAP 2',12,20);$('#umap-legend').innerHTML=byCount?'<span>Light: lower total counts · Dark: higher total counts</span>':d.labels.map((l,i)=>`<span style="--color:${d.colors[i]}">${esc(l)}</span>`).join('');const cfg=d.settings[current];$('#umap-summary').textContent=`${d.n.toLocaleString('en-US')} cells, one donor. ${cfg.n_neighbors} neighbors, minimum distance ${cfg.min_dist}; seed 42. Public 10x data (CC BY 4.0), Scanpy reference preprocessing and labels. These are precomputed layouts, not a live analysis of uploaded data.`;$('#umap-a').setAttribute('aria-pressed',String(current===0));$('#umap-b').setAttribute('aria-pressed',String(current===1));$('#umap-table').innerHTML=`<table class="mini-table"><thead><tr><th>Supplied label</th><th>Retained cells</th></tr></thead><tbody>${d.labels.map((l,i)=>`<tr><td>${esc(l)}</td><td>${d.groups.filter(x=>x===i).length}</td></tr>`).join('')}</tbody></table>`;};$('#umap-a').onclick=()=>{current=0;draw();};$('#umap-b').onclick=()=>{current=1;draw();};$('#umap-color').onchange=draw;draw();}
if($('#composition-range')){const draw=()=>{const v=M.composition(+$('#composition-range').value);$('#composition-value').textContent=v.a;$('#b-fraction').textContent=v.bPercent.toFixed(1)+'%';$('#all-count').textContent=v.total;$('#composition-bar').innerHTML=`<span style="width:${100-v.bPercent}%;background:#126b68">T cells</span><span style="width:${v.bPercent}%;background:#ac652c">B</span>`;$('#composition-note').textContent=`B-cell count stays at 20 while its fraction is ${v.bPercent.toFixed(1)}%. A relative decrease does not prove absolute depletion. This is arithmetic for one synthetic population, not a replicated statistical comparison.`;};$('#composition-range').oninput=draw;draw();}
if($('#pb-group')){const draw=()=>{const key=$('#pb-group').value,g=M.aggregate(key);$('#pb-body').innerHTML=Object.entries(g).map(([k,v])=>`<tr><td>${k}</td><td>${v.cells}</td><td>${v.count}</td></tr>`).join('');$('#pb-note').textContent=key==='condition'?'Two pooled profiles: donor replication and cell-type identity have been lost.':key==='donor'?'Four paired sample profiles: donor identity survives, but the cell types are still mixed. This does not answer a within-type expression question.':'Eight profiles preserve donor, condition and type. Analyze a comparable type with the paired design. This toy example has only two independent donors, not eight.';};$('#pb-group').onchange=draw;draw();}
if($('#de-output')){const t=['Gene A: statistical evidence for a very small estimated effect. Assess whether this magnitude matters for the question; FDR alone does not make the effect important.','Gene B: a moderate-to-large effect with evidence and consistency across donors. This is a candidate for follow-up, not proof of a mechanism.','Gene C: a large estimate but weaker evidence and donor inconsistency. Review uncertainty and outlier sensitivity instead of selecting solely by fold change.'];['a','b','c'].forEach((x,i)=>$('#deg-'+x).onclick=()=>{$('#de-output').textContent=t[i];['a','b','c'].forEach(y=>$('#deg-'+y).setAttribute('aria-pressed',String(y===x)));});}
if($('#signal-level')){const texts=['Candidate signaling relationship. Dissociation does not retain the original neighborhood, and RNA does not establish receptor activation.','Stronger support for localization and molecular plausibility. This remains observational evidence; a causal signaling effect is not yet demonstrated.','Functional evidence can strengthen the mechanism if the perturbation and readout are appropriate and alternative explanations are controlled. It still does not automatically establish clinical benefit.'];const draw=()=>$('#signal-output').textContent=texts[+$('#signal-level').value];$('#signal-level').onchange=draw;draw();}
if($('#trajectory-root')){const draw=()=>{const r=+$('#trajectory-root').value,dist=M.trajectory(r),max=Math.max(...dist),pos=[[65,130],[210,130],[355,130],[610,65],[610,205]],labels=['A','B','C','D','E'];$('#trajectory-svg').innerHTML=`<title>Fixed synthetic graph; root ${labels[r]}</title>${[[0,1],[1,2],[2,3],[2,4]].map(([a,b])=>`<line x1="${pos[a][0]}" y1="${pos[a][1]}" x2="${pos[b][0]}" y2="${pos[b][1]}" stroke="#a0b2c4" stroke-width="4"/>`).join('')}${pos.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="27" fill="hsl(175,50%,${75-dist[i]/max*48}%)" stroke="${i===r?'#c28408':'#142b45'}" stroke-width="${i===r?5:1}"/><text x="${x}" y="${y+5}" text-anchor="middle" font-size="17" font-family="Arial" fill="${dist[i]/max>.5?'white':'#142b45'}">${labels[i]}</text><text x="${x}" y="${y+48}" text-anchor="middle" font-size="13" font-family="Arial" fill="#142b45">${i===r?'Root':'Distance '+dist[i]}</text>`).join('')}`;$('#trajectory-output').textContent=`From root ${labels[r]}, distances are ${labels.map((l,i)=>l+'='+dist[i]).join(', ')}. The graph and measurements are unchanged. A different root changes the assigned ordering; these distances are not fitted pseudotime.`;};$('#trajectory-root').onchange=draw;draw();}
}
root.Labs={render,bind};
})(typeof window!=='undefined'?window:globalThis);
